### ISSUE TITLE
[Feature request] Allow keeping config in lua

### ISSUE THREAD

**Issue by ghostbuster91** [LintaoAmons/scratch.nvim#21]
Hi, nice plugin, congrats! 

One thing that bothers me is the decision to keep the config file in json. Sure I understand the need for simplicity, tough on the other hand lua is almost like json :) 

However, looking at your config I don't like that we need to refer to commands as strings (e.g. https://github.com/LintaoAmons/CoolStuffes/blob/main/lazyvim/.config/nvim/scratch_config.json#L196C24-L196C37). Instead I would much rather use lua to call another lua function. 

Ideally, if you ask me, I would drop the json config. But I understand that your vision for this plugin might be different. 

Another approach would be to abstract over config and let the user provide function that will provide a config either by reading it from a file or by just passing some lua objects. 

Would you be open for such a change?

Cheers,
Kasper

**Comment by LintaoAmons** [comment]
Thx~

Yeah, I thought about letting user choose the way they like to config the plugin.

Currently I can only think about completely have another branch that changes the config.lua 's implementation to lua instead of json.

Having thought out of a way to have them at the same time while keeping the configuration simple and intuitive

**Comment by LintaoAmons** [comment]
already config the plugin using lua, the convention way
