### ISSUE TITLE
See sub directories in open and go into

### ISSUE THREAD

**Issue by xavier-balesi** [LintaoAmons/scratch.nvim#5]
Hi and thank you for your plugin !

I think to be able to see the directories in the scratch directory and go into them will be a good feature ^^

**Comment by LintaoAmons** [comment]
> 

Sorry for didn't aware of the needs, recently when I want to have some golang scratch playground, I found a subdirectory is quite important since I have to have the main file in it's own directory.

I already impl the function and there's configuration that you can let the plugin create the directory automaticlly, and also you can find the scratch file inside the subdirectory
